context:
  version: 1.4.0

package:
  name: btop
  version: ${{ version }}

source:
  url: https://github.com/aristocratos/btop/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ac0d2371bf69d5136de7e9470c6fb286cbee2e16b4c7a6d2cd48a14796e86650

build:
  number: 0
  skip: [win]
  script:
    - if: osx
      then:
        - export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"
    - make -j$CPU_COUNT CXX=$CXX STRIP=true
    - make -j$CPU_COUNT PREFIX=$PREFIX install

requirements:
  build:
    - make
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}

tests:
  - script:
      - btop --version

about:
  homepage: https://github.com/aristocratos/btop
  repository: https://github.com/aristocratos/btop
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: Resource monitor that shows usage and stats for processor, memory, disks, network and processes.

extra:
  recipe-maintainers:
    - wolfv
