context:
  version: "1.4.3"

package:
  name: btop
  version: ${{ version }}

source:
  url: https://github.com/aristocratos/btop/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 81b133e59699a7fd89c5c54806e16452232f6452be9c14b3a634122e3ebed592

build:
  number: 0
  skip: [win]
  script:
    - if: osx
      then:
        - export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"
    - make -j$CPU_COUNT CXX=$CXX STRIP=true
    - make -j$CPU_COUNT PREFIX=$PREFIX install

requirements:
  build:
    - make
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}

tests:
  - script:
      - btop --version

about:
  homepage: https://github.com/aristocratos/btop
  repository: https://github.com/aristocratos/btop
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: Resource monitor that shows usage and stats for processor, memory, disks, network and processes.

extra:
  recipe-maintainers:
    - wolfv
